# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-sb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.proto.aruba_iot_types_pb2 as aruba__iot__types__pb2
import src.proto.aruba_iot_sb_action_pb2 as aruba__iot__sb__action__pb2
import src.proto.aruba_iot_sb_config_pb2 as aruba__iot__sb__config__pb2
import src.proto.aruba_iot_sb_status_pb2 as aruba__iot__sb__status__pb2
import src.proto.aruba_iot_sb_zb_pb2 as aruba__iot__sb__zb__pb2
import src.proto.aruba_iot_sb_serial_data_pb2 as aruba__iot__sb__serial__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-sb.proto',
  package='aruba_telemetry',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x61ruba-iot-sb.proto\x12\x0f\x61ruba_telemetry\x1a\x15\x61ruba-iot-types.proto\x1a\x19\x61ruba-iot-sb-action.proto\x1a\x19\x61ruba-iot-sb-config.proto\x1a\x19\x61ruba-iot-sb-status.proto\x1a\x15\x61ruba-iot-sb-zb.proto\x1a\x1e\x61ruba-iot-sb-serial-data.proto\"&\n\x08Receiver\x12\x0b\n\x03\x61ll\x18\x01 \x01(\x08\x12\r\n\x05\x61pMac\x18\x02 \x01(\x0c\"\xc6\x02\n\x0cIotSbMessage\x12#\n\x04meta\x18\x01 \x02(\x0b\x32\x15.aruba_telemetry.Meta\x12+\n\x08receiver\x18\x02 \x01(\x0b\x32\x19.aruba_telemetry.Receiver\x12(\n\x07\x61\x63tions\x18\x03 \x03(\x0b\x32\x17.aruba_telemetry.Action\x12\x30\n\x06\x63onfig\x18\x04 \x01(\x0b\x32 .aruba_telemetry.TransportConfig\x12.\n\x06status\x18\x05 \x01(\x0b\x32\x1e.aruba_telemetry.ConnectStatus\x12(\n\x06zigbee\x18\x06 \x01(\x0b\x32\x18.aruba_telemetry.SbZbMsg\x12.\n\x07sbSData\x18\x07 \x03(\x0b\x32\x1d.aruba_telemetry.SbSerialData')
  ,
  dependencies=[aruba__iot__types__pb2.DESCRIPTOR,aruba__iot__sb__action__pb2.DESCRIPTOR,aruba__iot__sb__config__pb2.DESCRIPTOR,aruba__iot__sb__status__pb2.DESCRIPTOR,aruba__iot__sb__zb__pb2.DESCRIPTOR,aruba__iot__sb__serial__data__pb2.DESCRIPTOR,])




_RECEIVER = _descriptor.Descriptor(
  name='Receiver',
  full_name='aruba_telemetry.Receiver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='all', full_name='aruba_telemetry.Receiver.all', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='apMac', full_name='aruba_telemetry.Receiver.apMac', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=236,
)


_IOTSBMESSAGE = _descriptor.Descriptor(
  name='IotSbMessage',
  full_name='aruba_telemetry.IotSbMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='aruba_telemetry.IotSbMessage.meta', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='aruba_telemetry.IotSbMessage.receiver', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actions', full_name='aruba_telemetry.IotSbMessage.actions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='aruba_telemetry.IotSbMessage.config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='aruba_telemetry.IotSbMessage.status', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zigbee', full_name='aruba_telemetry.IotSbMessage.zigbee', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sbSData', full_name='aruba_telemetry.IotSbMessage.sbSData', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=565,
)

_IOTSBMESSAGE.fields_by_name['meta'].message_type = aruba__iot__types__pb2._META
_IOTSBMESSAGE.fields_by_name['receiver'].message_type = _RECEIVER
_IOTSBMESSAGE.fields_by_name['actions'].message_type = aruba__iot__sb__action__pb2._ACTION
_IOTSBMESSAGE.fields_by_name['config'].message_type = aruba__iot__sb__config__pb2._TRANSPORTCONFIG
_IOTSBMESSAGE.fields_by_name['status'].message_type = aruba__iot__sb__status__pb2._CONNECTSTATUS
_IOTSBMESSAGE.fields_by_name['zigbee'].message_type = aruba__iot__sb__zb__pb2._SBZBMSG
_IOTSBMESSAGE.fields_by_name['sbSData'].message_type = aruba__iot__sb__serial__data__pb2._SBSERIALDATA
DESCRIPTOR.message_types_by_name['Receiver'] = _RECEIVER
DESCRIPTOR.message_types_by_name['IotSbMessage'] = _IOTSBMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Receiver = _reflection.GeneratedProtocolMessageType('Receiver', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVER,
  __module__ = 'aruba_iot_sb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.Receiver)
  ))
_sym_db.RegisterMessage(Receiver)

IotSbMessage = _reflection.GeneratedProtocolMessageType('IotSbMessage', (_message.Message,), dict(
  DESCRIPTOR = _IOTSBMESSAGE,
  __module__ = 'aruba_iot_sb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.IotSbMessage)
  ))
_sym_db.RegisterMessage(IotSbMessage)


# @@protoc_insertion_point(module_scope)
