# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-characteristic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-nb-characteristic.proto',
  package='aruba_telemetry',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!aruba-iot-nb-characteristic.proto\x12\x0f\x61ruba_telemetry\"\xab\x01\n\x0e\x43haracteristic\x12\x11\n\tdeviceMac\x18\x01 \x01(\x0c\x12\x13\n\x0bserviceUuid\x18\x02 \x01(\x0c\x12\x1a\n\x12\x63haracteristicUuid\x18\x03 \x01(\x0c\x12\r\n\x05value\x18\x04 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x31\n\nproperties\x18\x06 \x03(\x0e\x32\x1d.aruba_telemetry.CharProperty*\xa4\x01\n\x0c\x43harProperty\x12\r\n\tbroadcast\x10\x00\x12\x08\n\x04read\x10\x01\x12\x18\n\x14writeWithoutResponse\x10\x02\x12\x15\n\x11writeWithResponse\x10\x03\x12\n\n\x06notify\x10\x04\x12\x0c\n\x08indicate\x10\x05\x12\x0f\n\x0bsignedWrite\x10\x06\x12\x11\n\rwriteReliable\x10\x07\x12\x0c\n\x08writeAux\x10\x08')
)

_CHARPROPERTY = _descriptor.EnumDescriptor(
  name='CharProperty',
  full_name='aruba_telemetry.CharProperty',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='broadcast', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='read', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='writeWithoutResponse', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='writeWithResponse', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='notify', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='indicate', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='signedWrite', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='writeReliable', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='writeAux', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=229,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_CHARPROPERTY)

CharProperty = enum_type_wrapper.EnumTypeWrapper(_CHARPROPERTY)
broadcast = 0
read = 1
writeWithoutResponse = 2
writeWithResponse = 3
notify = 4
indicate = 5
signedWrite = 6
writeReliable = 7
writeAux = 8



_CHARACTERISTIC = _descriptor.Descriptor(
  name='Characteristic',
  full_name='aruba_telemetry.Characteristic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceMac', full_name='aruba_telemetry.Characteristic.deviceMac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceUuid', full_name='aruba_telemetry.Characteristic.serviceUuid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='characteristicUuid', full_name='aruba_telemetry.Characteristic.characteristicUuid', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='aruba_telemetry.Characteristic.value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='aruba_telemetry.Characteristic.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='aruba_telemetry.Characteristic.properties', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=226,
)

_CHARACTERISTIC.fields_by_name['properties'].enum_type = _CHARPROPERTY
DESCRIPTOR.message_types_by_name['Characteristic'] = _CHARACTERISTIC
DESCRIPTOR.enum_types_by_name['CharProperty'] = _CHARPROPERTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Characteristic = _reflection.GeneratedProtocolMessageType('Characteristic', (_message.Message,), dict(
  DESCRIPTOR = _CHARACTERISTIC,
  __module__ = 'aruba_iot_nb_characteristic_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.Characteristic)
  ))
_sym_db.RegisterMessage(Characteristic)


# @@protoc_insertion_point(module_scope)
