# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-nb-status.proto',
  package='aruba_telemetry',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x61ruba-iot-nb-status.proto\x12\x0f\x61ruba_telemetry\"\x1f\n\nConnUpdate\x12\x11\n\tmtu_value\x18\x01 \x01(\r\"\x90\x01\n\x06Status\x12\x11\n\tdeviceMac\x18\x01 \x01(\x0c\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.aruba_telemetry.statusValue\x12\x14\n\x0cstatusString\x18\x03 \x01(\t\x12/\n\nconnUpdate\x18\x04 \x01(\x0b\x32\x1b.aruba_telemetry.ConnUpdate*R\n\x0bstatusValue\x12\x16\n\x12\x64\x65viceDisconnected\x10\x00\x12\x15\n\x11inactivityTimeout\x10\x01\x12\x14\n\x10\x63onnectionUpdate\x10\x02')
)

_STATUSVALUE = _descriptor.EnumDescriptor(
  name='statusValue',
  full_name='aruba_telemetry.statusValue',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='deviceDisconnected', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='inactivityTimeout', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='connectionUpdate', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=308,
)
_sym_db.RegisterEnumDescriptor(_STATUSVALUE)

statusValue = enum_type_wrapper.EnumTypeWrapper(_STATUSVALUE)
deviceDisconnected = 0
inactivityTimeout = 1
connectionUpdate = 2



_CONNUPDATE = _descriptor.Descriptor(
  name='ConnUpdate',
  full_name='aruba_telemetry.ConnUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mtu_value', full_name='aruba_telemetry.ConnUpdate.mtu_value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=77,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='aruba_telemetry.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceMac', full_name='aruba_telemetry.Status.deviceMac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='aruba_telemetry.Status.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statusString', full_name='aruba_telemetry.Status.statusString', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connUpdate', full_name='aruba_telemetry.Status.connUpdate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=224,
)

_STATUS.fields_by_name['status'].enum_type = _STATUSVALUE
_STATUS.fields_by_name['connUpdate'].message_type = _CONNUPDATE
DESCRIPTOR.message_types_by_name['ConnUpdate'] = _CONNUPDATE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['statusValue'] = _STATUSVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnUpdate = _reflection.GeneratedProtocolMessageType('ConnUpdate', (_message.Message,), dict(
  DESCRIPTOR = _CONNUPDATE,
  __module__ = 'aruba_iot_nb_status_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ConnUpdate)
  ))
_sym_db.RegisterMessage(ConnUpdate)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'aruba_iot_nb_status_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.Status)
  ))
_sym_db.RegisterMessage(Status)


# @@protoc_insertion_point(module_scope)
