# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-nb-zb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.proto.aruba_iot_zb_types_pb2 as aruba__iot__zb__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-nb-zb.proto',
  package='aruba_telemetry',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x61ruba-iot-nb-zb.proto\x12\x0f\x61ruba_telemetry\x1a\x18\x61ruba-iot-zb-types.proto\"Q\n\nZbNbReport\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12%\n\x04\x65\x32pc\x18\x02 \x01(\x0b\x32\x17.aruba_telemetry.ZbE2PC\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"m\n\x07ZbNbAck\x12\r\n\x05reqid\x18\x01 \x01(\t\x12)\n\x06result\x18\x02 \x01(\x0e\x32\x19.aruba_telemetry.ZbResult\x12(\n\x04\x63ode\x18\x03 \x01(\x0e\x32\x1a.aruba_telemetry.ZbAckCode\"\x18\n\x07ZbNbRsp\x12\r\n\x05reqid\x18\x01 \x01(\t\"\x9c\x01\n\x07NbZbMsg\x12\x11\n\tradio_mac\x18\x01 \x01(\x0c\x12+\n\x06report\x18\x02 \x01(\x0b\x32\x1b.aruba_telemetry.ZbNbReport\x12%\n\x03\x61\x63k\x18\x03 \x01(\x0b\x32\x18.aruba_telemetry.ZbNbAck\x12*\n\x08response\x18\x04 \x01(\x0b\x32\x18.aruba_telemetry.ZbNbRsp')
  ,
  dependencies=[aruba__iot__zb__types__pb2.DESCRIPTOR,])




_ZBNBREPORT = _descriptor.Descriptor(
  name='ZbNbReport',
  full_name='aruba_telemetry.ZbNbReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='aruba_telemetry.ZbNbReport.mac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e2pc', full_name='aruba_telemetry.ZbNbReport.e2pc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='aruba_telemetry.ZbNbReport.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=149,
)


_ZBNBACK = _descriptor.Descriptor(
  name='ZbNbAck',
  full_name='aruba_telemetry.ZbNbAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqid', full_name='aruba_telemetry.ZbNbAck.reqid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='aruba_telemetry.ZbNbAck.result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='aruba_telemetry.ZbNbAck.code', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=260,
)


_ZBNBRSP = _descriptor.Descriptor(
  name='ZbNbRsp',
  full_name='aruba_telemetry.ZbNbRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqid', full_name='aruba_telemetry.ZbNbRsp.reqid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=286,
)


_NBZBMSG = _descriptor.Descriptor(
  name='NbZbMsg',
  full_name='aruba_telemetry.NbZbMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radio_mac', full_name='aruba_telemetry.NbZbMsg.radio_mac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='report', full_name='aruba_telemetry.NbZbMsg.report', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack', full_name='aruba_telemetry.NbZbMsg.ack', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='aruba_telemetry.NbZbMsg.response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=445,
)

_ZBNBREPORT.fields_by_name['e2pc'].message_type = aruba__iot__zb__types__pb2._ZBE2PC
_ZBNBACK.fields_by_name['result'].enum_type = aruba__iot__zb__types__pb2._ZBRESULT
_ZBNBACK.fields_by_name['code'].enum_type = aruba__iot__zb__types__pb2._ZBACKCODE
_NBZBMSG.fields_by_name['report'].message_type = _ZBNBREPORT
_NBZBMSG.fields_by_name['ack'].message_type = _ZBNBACK
_NBZBMSG.fields_by_name['response'].message_type = _ZBNBRSP
DESCRIPTOR.message_types_by_name['ZbNbReport'] = _ZBNBREPORT
DESCRIPTOR.message_types_by_name['ZbNbAck'] = _ZBNBACK
DESCRIPTOR.message_types_by_name['ZbNbRsp'] = _ZBNBRSP
DESCRIPTOR.message_types_by_name['NbZbMsg'] = _NBZBMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZbNbReport = _reflection.GeneratedProtocolMessageType('ZbNbReport', (_message.Message,), dict(
  DESCRIPTOR = _ZBNBREPORT,
  __module__ = 'aruba_iot_nb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbNbReport)
  ))
_sym_db.RegisterMessage(ZbNbReport)

ZbNbAck = _reflection.GeneratedProtocolMessageType('ZbNbAck', (_message.Message,), dict(
  DESCRIPTOR = _ZBNBACK,
  __module__ = 'aruba_iot_nb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbNbAck)
  ))
_sym_db.RegisterMessage(ZbNbAck)

ZbNbRsp = _reflection.GeneratedProtocolMessageType('ZbNbRsp', (_message.Message,), dict(
  DESCRIPTOR = _ZBNBRSP,
  __module__ = 'aruba_iot_nb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbNbRsp)
  ))
_sym_db.RegisterMessage(ZbNbRsp)

NbZbMsg = _reflection.GeneratedProtocolMessageType('NbZbMsg', (_message.Message,), dict(
  DESCRIPTOR = _NBZBMSG,
  __module__ = 'aruba_iot_nb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.NbZbMsg)
  ))
_sym_db.RegisterMessage(NbZbMsg)


# @@protoc_insertion_point(module_scope)
