# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-sb-serial-data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-sb-serial-data.proto',
  package='aruba_telemetry',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x61ruba-iot-sb-serial-data.proto\x12\x0f\x61ruba_telemetry\";\n\x0cSbSerialData\x12\x12\n\nsbDeviceId\x18\x01 \x01(\t\x12\x17\n\x0fsbSerialPayload\x18\x02 \x01(\x0c')
)




_SBSERIALDATA = _descriptor.Descriptor(
  name='SbSerialData',
  full_name='aruba_telemetry.SbSerialData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sbDeviceId', full_name='aruba_telemetry.SbSerialData.sbDeviceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sbSerialPayload', full_name='aruba_telemetry.SbSerialData.sbSerialPayload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['SbSerialData'] = _SBSERIALDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SbSerialData = _reflection.GeneratedProtocolMessageType('SbSerialData', (_message.Message,), dict(
  DESCRIPTOR = _SBSERIALDATA,
  __module__ = 'aruba_iot_sb_serial_data_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.SbSerialData)
  ))
_sym_db.RegisterMessage(SbSerialData)


# @@protoc_insertion_point(module_scope)
