# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aruba-iot-sb-zb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import src.proto.aruba_iot_zb_types_pb2 as aruba__iot__zb__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aruba-iot-sb-zb.proto',
  package='aruba_telemetry',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x61ruba-iot-sb-zb.proto\x12\x0f\x61ruba_telemetry\x1a\x18\x61ruba-iot-zb-types.proto\"^\n\x08ZbSbSend\x12\r\n\x05reqid\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\x0c\x12%\n\x04\x65\x32pc\x18\x03 \x01(\x0b\x32\x17.aruba_telemetry.ZbE2PC\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"\x19\n\x08ZbSbRead\x12\r\n\x05reqid\x18\x01 \x01(\t\"\x1a\n\tZbSbWrite\x12\r\n\x05reqid\x18\x01 \x01(\t\"\x1b\n\nZbSbAction\x12\r\n\x05reqid\x18\x01 \x01(\t\"\x8a\x01\n\x07ZbSbReq\x12\'\n\x04read\x18\x01 \x01(\x0b\x32\x19.aruba_telemetry.ZbSbRead\x12)\n\x05write\x18\x02 \x01(\x0b\x32\x1a.aruba_telemetry.ZbSbWrite\x12+\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x1b.aruba_telemetry.ZbSbAction\"p\n\x07SbZbMsg\x12\x11\n\tradio_mac\x18\x01 \x01(\x0c\x12\'\n\x04send\x18\x02 \x01(\x0b\x32\x19.aruba_telemetry.ZbSbSend\x12)\n\x07request\x18\x03 \x01(\x0b\x32\x18.aruba_telemetry.ZbSbReq')
  ,
  dependencies=[aruba__iot__zb__types__pb2.DESCRIPTOR,])




_ZBSBSEND = _descriptor.Descriptor(
  name='ZbSbSend',
  full_name='aruba_telemetry.ZbSbSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqid', full_name='aruba_telemetry.ZbSbSend.reqid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='aruba_telemetry.ZbSbSend.mac', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e2pc', full_name='aruba_telemetry.ZbSbSend.e2pc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='aruba_telemetry.ZbSbSend.payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=162,
)


_ZBSBREAD = _descriptor.Descriptor(
  name='ZbSbRead',
  full_name='aruba_telemetry.ZbSbRead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqid', full_name='aruba_telemetry.ZbSbRead.reqid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=189,
)


_ZBSBWRITE = _descriptor.Descriptor(
  name='ZbSbWrite',
  full_name='aruba_telemetry.ZbSbWrite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqid', full_name='aruba_telemetry.ZbSbWrite.reqid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=217,
)


_ZBSBACTION = _descriptor.Descriptor(
  name='ZbSbAction',
  full_name='aruba_telemetry.ZbSbAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqid', full_name='aruba_telemetry.ZbSbAction.reqid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=246,
)


_ZBSBREQ = _descriptor.Descriptor(
  name='ZbSbReq',
  full_name='aruba_telemetry.ZbSbReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read', full_name='aruba_telemetry.ZbSbReq.read', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write', full_name='aruba_telemetry.ZbSbReq.write', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='aruba_telemetry.ZbSbReq.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=387,
)


_SBZBMSG = _descriptor.Descriptor(
  name='SbZbMsg',
  full_name='aruba_telemetry.SbZbMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radio_mac', full_name='aruba_telemetry.SbZbMsg.radio_mac', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='send', full_name='aruba_telemetry.SbZbMsg.send', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='aruba_telemetry.SbZbMsg.request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=501,
)

_ZBSBSEND.fields_by_name['e2pc'].message_type = aruba__iot__zb__types__pb2._ZBE2PC
_ZBSBREQ.fields_by_name['read'].message_type = _ZBSBREAD
_ZBSBREQ.fields_by_name['write'].message_type = _ZBSBWRITE
_ZBSBREQ.fields_by_name['action'].message_type = _ZBSBACTION
_SBZBMSG.fields_by_name['send'].message_type = _ZBSBSEND
_SBZBMSG.fields_by_name['request'].message_type = _ZBSBREQ
DESCRIPTOR.message_types_by_name['ZbSbSend'] = _ZBSBSEND
DESCRIPTOR.message_types_by_name['ZbSbRead'] = _ZBSBREAD
DESCRIPTOR.message_types_by_name['ZbSbWrite'] = _ZBSBWRITE
DESCRIPTOR.message_types_by_name['ZbSbAction'] = _ZBSBACTION
DESCRIPTOR.message_types_by_name['ZbSbReq'] = _ZBSBREQ
DESCRIPTOR.message_types_by_name['SbZbMsg'] = _SBZBMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZbSbSend = _reflection.GeneratedProtocolMessageType('ZbSbSend', (_message.Message,), dict(
  DESCRIPTOR = _ZBSBSEND,
  __module__ = 'aruba_iot_sb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbSbSend)
  ))
_sym_db.RegisterMessage(ZbSbSend)

ZbSbRead = _reflection.GeneratedProtocolMessageType('ZbSbRead', (_message.Message,), dict(
  DESCRIPTOR = _ZBSBREAD,
  __module__ = 'aruba_iot_sb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbSbRead)
  ))
_sym_db.RegisterMessage(ZbSbRead)

ZbSbWrite = _reflection.GeneratedProtocolMessageType('ZbSbWrite', (_message.Message,), dict(
  DESCRIPTOR = _ZBSBWRITE,
  __module__ = 'aruba_iot_sb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbSbWrite)
  ))
_sym_db.RegisterMessage(ZbSbWrite)

ZbSbAction = _reflection.GeneratedProtocolMessageType('ZbSbAction', (_message.Message,), dict(
  DESCRIPTOR = _ZBSBACTION,
  __module__ = 'aruba_iot_sb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbSbAction)
  ))
_sym_db.RegisterMessage(ZbSbAction)

ZbSbReq = _reflection.GeneratedProtocolMessageType('ZbSbReq', (_message.Message,), dict(
  DESCRIPTOR = _ZBSBREQ,
  __module__ = 'aruba_iot_sb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.ZbSbReq)
  ))
_sym_db.RegisterMessage(ZbSbReq)

SbZbMsg = _reflection.GeneratedProtocolMessageType('SbZbMsg', (_message.Message,), dict(
  DESCRIPTOR = _SBZBMSG,
  __module__ = 'aruba_iot_sb_zb_pb2'
  # @@protoc_insertion_point(class_scope:aruba_telemetry.SbZbMsg)
  ))
_sym_db.RegisterMessage(SbZbMsg)


# @@protoc_insertion_point(module_scope)
